# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

global:
  dnsDomain: green.house
  dex:
    backend: postgres
    postgresql:
      postgresqlDatabase: dex
      postgresqlPort: 5432
      postgresqlUsername: dex
  plugin:
    optionValueTemplating: false

controllerManager:
  args:
    foo: bar

alerts:
  enabled: true
  commonAlertLabels:
    foo: bar
    cluster: test
