apiVersion: v1
kind: Service
metadata:
  name: {{ include "authz.fullname" . }}
  labels:
    {{- include "authz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 32443
      protocol: TCP
      name: http
  selector:
    {{- include "authz.selectorLabels" . | nindent 4 }}
