# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

global:
  dnsDomain: green.house
  dex:
    backend: kubernetes
  template:
    rendering: false
alerts:
  enabled: false
certManager:
  enabled: false