# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

version: "2.1"

services:
  envtest:
    image: ghcr.io/cloudoperators/greenhouse-dev-env:main
    volumes:
      - ./envtest:/envtest
      - ./webhook-certs:/webhook-certs
    network_mode: host
    environment:
      # one of ["test-org-admin", "test-org-member"] - leave unset for "cluster-admin"
      - DEV_ENV_CONTEXT
      # set to true for control plane output
      - KUBEBUILDER_ATTACH_CONTROL_PLANE_OUTPUT=false
    healthcheck:
      test: ["CMD", "cat", "/tmp/.envtest-running"]
      interval: 10s
      timeout: 10s
      retries: 5
  cmanager:
    image: ghcr.io/cloudoperators/greenhouse:main
    environment:
      - KUBECONFIG=/envtest/internal.kubeconfig
      - HEADSCALE_API_URL=mock_empty
      - HEADSCALE_API_KEY=mock_empty
      - TAILSCALE_PROXY=mock_empty
    volumes:
      - ./envtest:/envtest
      - ./webhook-certs:/tmp/k8s-webhook-server/serving-certs
    depends_on:
      envtest:
        condition: service_healthy
    network_mode: service:envtest
    command: --dns-domain localhost
  bootstrap:
    image: ghcr.io/cloudoperators/greenhouse-dev-env:main
    environment:
      - KUBECONFIG=/envtest/internal.kubeconfig
    volumes:
      - ./envtest:/envtest
      - ./bootstrap:/bootstrap
    command: kubectl apply -f /bootstrap
    depends_on:
      - cmanager
    network_mode: service:envtest
    restart: on-failure:5
