name: backport
on:
  pull_request_target:
    types: [closed, labeled]

jobs:
  backport:
    if: github.event.pull_request.state == 'closed' && github.event.pull_request.merged && (github.event_name != 'labeled' || startsWith('backport:', github.event.label.name))
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.CLOUDOPERATOR_APP_ID }}
          private-key: ${{ secrets.CLOUDOPERATOR_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ steps.github-app-token.outputs.token }}
      - name: Create backport PRs
        uses: korthout/backport-action@c656f5d5851037b2b38fb5db2691a03fa229e3b2 # v4.0.1
        # xref: https://github.com/korthout/backport-action#inputs
        with:
          # Use token to allow workflows to be triggered for the created PR
          github_token: ${{ steps.github-app-token.outputs.token }}
          # Match labels with a pattern `backport:<target-branch>`
          label_pattern: '^backport:(release\/v[0-9]+.[0-9]+)$'
          # A bit shorter pull-request title than the default
          pull_title: 'backport(${target_branch}): ${pull_title}'
          # Simpler PR description than default
          pull_description: |-
            Automated cherry-pick to `${target_branch}`, triggered by a label in PR#${pull_number}.
          # Name and Email of the cloud-operator-bot, used commit the cherry-pick & create the PR
          git_commiter_name: cloud-operator-bot[bot]
          git_commiter_email: 224791424+cloud-operator-bot[bot]@users.noreply.github.com
